### ISSUE TITLE
accodion不能用block条件渲染

### ISSUE THREAD

**Issue by 1173710113** [vivoquickapp/apex-ui#2]
`  <my-accordition-group id="node-list" accordion="{{true}}">
            <block for="nodeLists">
                <my-accordion group-id="node-list" title="{{$item.content}}" content="自定义组件自定义组件自定义组件自定义组件自定义组件"></my-accordion>
            </block>
        </my-accordition-group>`
![RBTUVHZUIG0 E52YGHQE$RT](https://user-images.githubusercontent.com/47938849/72791535-72e88200-3c72-11ea-956b-88379533ac4c.png)
![(LT S368QHJDYUC5ESXMW2](https://user-images.githubusercontent.com/47938849/72791597-8bf13300-3c72-11ea-9fff-bb91df9b023e.png)

**Comment by stevendong** [comment]
有测试可用block条件渲染，需要具体看下你那边项目的情况，可以加一下我们微信沟通一下vivo-technology
