### ISSUE TITLE
无法监听my-textarea触发的emit事件

### ISSUE THREAD

**Issue by Gd-Lianjy** [vivoquickapp/apex-ui#6]
my-textarea组件内onChange触发this.$emit("textareaChange") 事件，但是在组件引用页无法通过$on("textareaChange")监听到该事件，无法获取到该组件输入的值

**Comment by Bazinga-2333** [comment]
this.$emit("textareaChange") 触发的事件需要在组件上使用ontextarea-change绑定事件监听函数
